# Generated by Django 6.0 on 2025-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_sympathizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sympathizer',
            name='link_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
