# Generated by Django 6.0 on 2025-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_sympathizer_link_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sympathizer',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
