# Generated by Django 6.0.1 on 2026-01-19 16:31

import django.db.models.deletion
import referrals.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_sympathizer_activated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSympathizer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], max_length=1)),
                ('referral_code', models.CharField(db_index=True, default=referrals.models.generate_referral_code, editable=False, max_length=8)),
                ('link_enabled', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Si está suspendido, no puede acceder al sistema')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Simpatizante',
                'verbose_name_plural': 'historical Simpatizantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='sympathizer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Simpatizante', 'verbose_name_plural': 'Simpatizantes'},
        ),
        migrations.AddField(
            model_name='sympathizer',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Si está suspendido, no puede acceder al sistema'),
        ),
        migrations.AddField(
            model_name='sympathizer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='referral_code',
            field=models.CharField(db_index=True, default=referrals.models.generate_referral_code, editable=False, max_length=8, unique=True),
        ),
        migrations.AddIndex(
            model_name='sympathizer',
            index=models.Index(fields=['nombres', 'apellidos'], name='referrals_s_nombres_0d178c_idx'),
        ),
        migrations.AddIndex(
            model_name='sympathizer',
            index=models.Index(fields=['referrer'], name='referrals_s_referre_0c8851_idx'),
        ),
        migrations.AddField(
            model_name='historicalsympathizer',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referrals.department'),
        ),
        migrations.AddField(
            model_name='historicalsympathizer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsympathizer',
            name='municipio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referrals.municipality'),
        ),
        migrations.AddField(
            model_name='historicalsympathizer',
            name='referrer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referrals.sympathizer'),
        ),
        migrations.AddField(
            model_name='historicalsympathizer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
