# Generated by Django 6.0.1 on 2026-01-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_historicalsympathizer_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsympathizer',
            name='network_name',
            field=models.CharField(blank=True, help_text='Nombre de la red/político (solo para fundadores)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sympathizer',
            name='network_name',
            field=models.CharField(blank=True, help_text='Nombre de la red/político (solo para fundadores)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.department'),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sympathizer',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.municipality'),
        ),
    ]
